version: '3'

services:
  # Data base
  core-db:
    image: postgres:latest
    restart: always
    ports:
      - "5400:5432"
    environment:
      POSTGRES_DB: memorizing-core
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - net

  telegram-bot-db:
    image: postgres:latest
    restart: always
    ports:
      - "5401:5432"
    environment:
      POSTGRES_DB: memorizing-telegram-bot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
        - net

  # Environment
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8888:8888"
    networks:
      - net

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8761:8761"
    environment:
      LOCALHOST: ${LOCALHOST}
    depends_on:
      - config-server
    networks:
      - net

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8765:8765"
    environment:
      LOCALHOST: ${LOCALHOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
    depends_on:
      - config-server
      - eureka-server
      - core-service
      - telegram-bot-service
    networks:
      - net

  # Services
  core-service:
    build:
      context: ./memorizing-core
      dockerfile: Dockerfile
    restart: always
    environment:
      LOCALHOST: ${LOCALHOST}
    volumes:
      - core-db-data:/var/lib/postgresql/data
    depends_on:
      - core-db
      - config-server
      - eureka-server
    networks:
      - net

  telegram-bot-service:
    build:
      context: ./memorizing-telegram-bot
      dockerfile: Dockerfile
    restart: always

    ports:
      - "8000:8000"

    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
      LOCALHOST: ${LOCALHOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
    volumes:
      - telegram-bot-db-data:/var/lib/postgresql/data
    depends_on:
      - telegram-bot-db
      - config-server
      - eureka-server
    networks:
      - net

volumes:
  telegram-bot-db-data:
  core-db-data:

networks:
  net:
    driver: bridge