version: '3'

services:
  # Data base
  core-db:
    image: postgres:latest
    restart: always
    ports:
      - "5400:5432"
    environment:
      POSTGRES_DB: memorizing-core
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - net

  telegram-bot-db:
    image: postgres:latest
    restart: always
    ports:
      - "5401:5432"
    environment:
      POSTGRES_DB: memorizing-telegram-bot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
        - net

  # Environment
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      SPRING_PROFILES_ACTIVE: docker, prod
    ports:
      - "8888:8888"
    networks:
      - net

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker, prod
      LOCALHOST: ${LOCALHOST}
    depends_on:
      - config-server
    networks:
      - net

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "8765:8765"
    environment:
      SPRING_PROFILES_ACTIVE: docker, prod
      LOCALHOST: ${LOCALHOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
    depends_on:
      - config-server
      - eureka-server
      - core-service
      - telegram-bot-service
    networks:
      - net

  rabbitmq:
    image: rabbitmq:3.9.29-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "15672:15672"
      - "5672:5672"

  # Services
  core-service:
    build:
      context: ./memorizing-core
      dockerfile: Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      SPRING_PROFILES_ACTIVE: docker, prod, rest
      LOCALHOST: ${LOCALHOST}
    volumes:
      - core-db-data:/var/lib/postgresql/data
    depends_on:
      - core-db
      - config-server
      - eureka-server
    networks:
      - net

  telegram-bot-service:
    build:
      context: ./memorizing-telegram-bot
      dockerfile: Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "8000:8000"
    environment:
      SPRING_PROFILES_ACTIVE: docker, prod, rest
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      LOCALHOST: ${LOCALHOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
    volumes:
      - telegram-bot-db-data:/var/lib/postgresql/data
    depends_on:
      - telegram-bot-db
      - config-server
      - eureka-server
    networks:
      - net

volumes:
  telegram-bot-db-data:
  core-db-data:

networks:
  net:
    driver: bridge